package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/handler/extension"
	"github.com/99designs/gqlgen/graphql/handler/lru"
	"github.com/99designs/gqlgen/graphql/handler/transport"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/joho/godotenv"
	"github.com/tarangrastogi/graphql_gqlgen/graph"
	"github.com/tarangrastogi/graphql_gqlgen/internal/auth"
	loader "github.com/tarangrastogi/graphql_gqlgen/internal/dataloader"
	"github.com/tarangrastogi/graphql_gqlgen/internal/db"
	manualmodels "github.com/tarangrastogi/graphql_gqlgen/internal/manualmodel"
	"github.com/tarangrastogi/graphql_gqlgen/internal/repository"
	"github.com/tarangrastogi/graphql_gqlgen/internal/service"
	"github.com/vektah/gqlparser/v2/ast"
)

const defaultPort = "8080"

func main() {
	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}
	port := os.Getenv("PORT")
	if port == "" {
		port = defaultPort
	}
	fmt.Println("HOST:", os.Getenv("DB_HOST"))
	fmt.Println("PORT:", os.Getenv("DB_PORT"))
	fmt.Println("USER:", os.Getenv("DB_USER"))
	fmt.Println("PASSWORD:", os.Getenv("DB_PASSWORD"))
	fmt.Println("DB:", os.Getenv("DB_NAME"))
	pool, err := db.NewPostgresConnection()

	if err != nil {
		log.Fatal(err)
	}

	userRepo := repository.NewUserRepository(pool)
	postRepo := repository.NewPostRepository(pool)
	commentRepo := repository.NewCommentRepository(pool)

	userService := service.NewUserService(userRepo)
	postService := service.NewPostService(postRepo, userRepo)
	commentService := service.NewCommentService(commentRepo, userRepo, postRepo)

	srv := handler.New(graph.NewExecutableSchema(graph.Config{Resolvers: &graph.Resolver{
		UserCreatedChan:    make(chan *manualmodels.User),
		PostCreatedChan:    make(chan *manualmodels.Post),
		CommentCreatedChan: make(chan *manualmodels.Comment),
		UserService:        userService,
		PostService:        postService,
		CommentService:     commentService,
	}}))

	srv.AddTransport(transport.Options{})
	srv.AddTransport(transport.Websocket{
		KeepAlivePingInterval: 10 * time.Second,
	})

	srv.AddTransport(transport.GET{})
	srv.AddTransport(transport.POST{})

	srv.SetQueryCache(lru.New[*ast.QueryDocument](1000))

	srv.Use(extension.Introspection{})
	srv.Use(extension.AutomaticPersistedQuery{
		Cache: lru.New[string](100),
	})

	http.Handle("/", playground.Handler("GraphQL playground", "/query"))
	
	
	//version 1
	//http.Handle("/query", srv)

	//version2
	// http.Handle("/query", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	// 	//this is a batch loading middleware that optimizes batch requests and prevents the N+1 problem
	// 	loaders := loader.NewLoaders(
	// 		userService,
	// 		postService,
	// 		commentService,
	// 	)

	// 	ctx := loader.WithLoaders(
	// 		r.Context(),
	// 		loaders,
	// 	)

	// 	srv.ServeHTTP(
	// 		w,
	// 		r.WithContext(ctx),
	// 	)
	// }))

	//injecting the middlewares before heeing the /query handler

	graphqlHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

		loaders := loader.NewLoaders(
			userService,
			postService,
			commentService,
		)

		ctx := loader.WithLoaders(
			r.Context(),
			loaders,
		)

		srv.ServeHTTP(
			w,
			r.WithContext(ctx),
		)
	})
	protectedHandler := auth.Middleware(graphqlHandler)

	http.Handle("/query", protectedHandler)   //protectHandler -> batchloadermiddleware -> autogenerated gql /query handler

	log.Printf("connect to http://localhost:%s/ for GraphQL playground", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))

}
