package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"fmt"
	"log"
	"strconv"

	"github.com/tarangrastogi/graphql_gqlgen/graph/model"
	"github.com/tarangrastogi/graphql_gqlgen/internal/mapper"
)

// Post is the resolver for the post field.
func (r *commentResolver) Post(ctx context.Context, obj *model.Comment) (*model.Post, error) {
	//panic(fmt.Errorf("not implemented: Post - post"))

	//HARDCODE
	// switch obj.ID {
	// case "1":
	// 	return &model.Post{
	// 		ID:      "1",
	// 		Title:   "First Post",
	// 		Content: "This is the content of the first post.",
	// 	}, nil
	// case "2":
	// 	return &model.Post{
	// 		ID:      "2",
	// 		Title:   "Second Post",
	// 		Content: "This is the content of the second post.",
	// 	}, nil
	// }

	//Actual crud

	return nil, fmt.Errorf("No post found for comment with ID %s", obj.ID)
}

// Author is the resolver for the author field.
func (r *commentResolver) Author(ctx context.Context, obj *model.Comment) (*model.User, error) {
	//	panic(fmt.Errorf("not implemented: Author - author"))

	switch obj.ID {
	case "1":
		return &model.User{
			ID:   "1",
			Name: "John Doe",
			Age:  30,
		}, nil
	case "2":
		return &model.User{
			ID:   "2",
			Name: "Jane Smith",
			Age:  25,
		}, nil
	}

	return nil, fmt.Errorf("No author found for comment with ID %s", obj.ID)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	// //panic(fmt.Errorf("not implemented: CreateUser - createUser"))
	// log.Printf("Creating user with name: %s and age: %d", input.Name, input.Age)

	// //generating a unique ID for the new user (in a real application, this would be handled by the database)
	// var id int
	// id = rand.Intn(1000) // Generate a random ID for demonstration purposes

	// log.Printf("Generated user ID: %d", id)
	// // Simulate creating a user and returning the created user
	// var user *model.User = &model.User{
	// 	ID:   fmt.Sprintf("%d", id), // In a real application, this would be generated by the database
	// 	Name: input.Name,
	// 	Age:  input.Age,
	// }

	entityUser := mapper.ToEntityUser(input)

	user, err := r.UserService.Create(ctx, entityUser)
	if err != nil {
		return nil, err
	}

	graphQLUser := mapper.ToGraphQLUser(user)

	go func() {
		log.Printf("Sending new user to UserCreated channel: %+v", graphQLUser)
		r.UserCreatedChan <- graphQLUser
	}()

	return graphQLUser, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	//panic(fmt.Errorf("not implemented: CreatePost - createPost"))
	// post := &model.Post{
	// 	ID:      "1",
	// 	Title:   input.Title,
	// 	Content: input.Content,
	// }
	// go func() {
	// 	log.Printf("Sending new post to PostCreated channel: %+v", post)
	// 	r.PostCreatedChan <- post
	// }()
	// return post, nil

	//actual implementation
	entityPost, err := mapper.ToEntityPost(input)
	if err != nil {
		return nil, err
	}

	post, err := r.PostService.Create(ctx, entityPost)
	if err != nil {
		return nil, err
	}

	graphQLPost := mapper.ToGraphQLPost(post)

	go func() {
		r.PostCreatedChan <- graphQLPost
	}()

	return graphQLPost, nil

}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*model.Comment, error) {
	//panic(fmt.Errorf("not implemented: CreateComment - createComment"))
	// comment := &model.Comment{
	// 	ID:      "1",
	// 	Content: input.Content,
	// }
	// go func() {
	// 	log.Printf("Sending new comment to CommentCreated channel: %+v", comment)
	// 	r.CommentCreatedChan <- comment
	// }()
	// return comment, nil

	entityComment, err := mapper.ToEntityComment(input)
	if err != nil {
		return nil, err
	}

	comment, err := r.CommentService.Create(ctx, entityComment)
	if err != nil {
		return nil, err
	}

	graphQLComment := mapper.ToGraphQLComment(comment)

	go func() {
		r.CommentCreatedChan <- graphQLComment
	}()

	return graphQLComment, nil

}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *model.Post) (*model.User, error) {
	//panic(fmt.Errorf("not implemented: Author - author"))

	//checks the posts id and returns the author of the post
	switch obj.ID {
	case "1":
		return &model.User{
			ID:   "1",
			Name: "John Doe",
			Age:  30,
		}, nil
	case "2":
		return &model.User{
			ID:   "2",
			Name: "Jane Smith",
			Age:  25,
		}, nil
	}

	return nil, fmt.Errorf("No author found for post with ID %s", obj.ID)
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post) ([]*model.Comment, error) {
	//panic(fmt.Errorf("not implemented: Comments - comments"))

	//checks the posts id and return its comments
	// switch obj.ID {
	// case "1":
	// 	return []*model.Comment{
	// 		{
	// 			ID:      "1",
	// 			Content: "This is a comment on the first post.",
	// 		},
	// 		{
	// 			ID:      "2",
	// 			Content: "This is another comment on the first post.",
	// 		},
	// 	}, nil
	// case "2":
	// 	return []*model.Comment{
	// 		{
	// 			ID:      "1",
	// 			Content: "This is a comment on the second post.",
	// 		},
	// 		{
	// 			ID:      "2",
	// 			Content: "This is another comment on the second post.",
	// 		},
	// 	}, nil

	// }

	return nil, fmt.Errorf("No comments found for post with ID %s", obj.ID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	//panic(fmt.Errorf("not implemented: Users - users"))
	// return []*model.User{
	// 	{
	// 		ID:   "1",
	// 		Name: "John Doe",
	// 		Age:  30,
	// 	},
	// 	{
	// 		ID:   "2",
	// 		Name: "Jane Smith",
	// 		Age:  25,
	// 	},
	// }, nil

	users, err := r.UserService.GetAll(ctx)

	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLUsers(users), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	//panic(fmt.Errorf("not implemented: User - user"))
	// log.Printf("Fetching user with ID: %s", id)

	// // Simulate fetching user from a data source
	// if id == "1" {
	// 	return &model.User{
	// 		ID:   "1",
	// 		Name: "John Doe",
	// 		Age:  30,
	// 	}, nil
	// } else if id == "2" {
	// 	return &model.User{
	// 		ID:   "2",
	// 		Name: "Jane Smith",
	// 		Age:  25,
	// 	}, nil
	// } else {
	// 	return nil, fmt.Errorf("User with ID %s not found", id)
	// }

	//actual db implementation

	userId, err := strconv.ParseInt(id, 10, 64)

	if err != nil {
		return nil, err
	}

	user, err := r.UserService.GetByID(ctx, userId)

	if err != nil {
		return nil, err
	}
	return mapper.ToGraphQLUser(user), nil

}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	//panic(fmt.Errorf("not implemented: Posts - posts"))
	// return []*model.Post{
	// 	{
	// 		ID:      "1",
	// 		Title:   "First Post",
	// 		Content: "Thintent ofst post.",
	// 	},
	// 	{
	// 		ID:      "2",
	// 		Title:   "Second Post",
	// 		Content: "This is the of the second post.",
	// 	},
	// }, nil

	posts, err := r.PostService.GetAll(ctx)

	if err != nil {
		return nil, err
	}

	return mapper.ToGraphQLPosts(posts), nil

}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*model.Post, error) {
	//panic(fmt.Errorf("not implemented: Post - post"))
	// return &model.Post{
	// 	ID:      id,
	// 	Title:   fmt.Sprintf("Post %s", id),
	// 	Content: fmt.Sprintf("This is the content of post %s.", id),
	// }, nil

	postId, err := strconv.ParseInt(id, 10, 64)

	if err != nil {
		return nil, fmt.Errorf("Invalid post id: %w", err)
	}

	post, err := r.PostService.GetByID(ctx, postId)

	if err != nil {
		return nil, err
	}

	return mapper.ToGraphQLPost(post), nil

}

// UserCreated is the resolver for the userCreated field.
func (r *subscriptionResolver) UserCreated(ctx context.Context) (<-chan *model.User, error) {
	//panic(fmt.Errorf("not implemented: UserCreated - userCreated"))
	return r.UserCreatedChan, nil
}

// PostCreated is the resolver for the postCreated field.
func (r *subscriptionResolver) PostCreated(ctx context.Context) (<-chan *model.Post, error) {
	//panic(fmt.Errorf("not implemented: PostCreated - postCreated"))
	return r.PostCreatedChan, nil
}

// CommentCreated is the resolver for the commentCreated field.
func (r *subscriptionResolver) CommentCreated(ctx context.Context) (<-chan *model.Comment, error) {
	//panic(fmt.Errorf("not implemented: CommentCreated - commentCreated"))
	return r.CommentCreatedChan, nil
}






// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User) ([]*model.Post, error) {
	// switch obj.ID {
	// case "1":
	// 	return []*model.Post{
	// 		{
	// 			ID:      "1",
	// 			Title:   "First Post",
	// 			Content: "This is the content of the first post.",
	// 		},
	// 		{
	// 			ID:      "2",
	// 			Title:   "Second Post",
	// 			Content: "This is the content of the second post.",
	// 		},
	// 	}, nil
	// case "2":
	// 	return []*model.Post{
	// 		{
	// 			ID:      "3",
	// 			Title:   "Third Post",
	// 			Content: "This is the content of the third post.",
	// 		},
	// 		{
	// 			ID:      "4",
	// 			Title:   "Fourth Post",
	// 			Content: "This is the content of the fourth post.",
	// 		},
	// 	}, nil
	// }

	userId , err := strconv.ParseInt(obj.ID , 10 , 64)
	if(err != nil ){
		return nil  , err
	}

	posts , err := r.PostService.GetByUserID(ctx , userId)
	
	//now map these psosts to the graphql equivalent 
	if err != nil {
		return nil , err
	}

	return mapper.ToGraphQLPosts(posts) , nil
	// return nil, fmt.Errorf("No posts found for user with ID %s", obj.ID)
}

// Comments is the resolver for the comments field.
func (r *userResolver) Comments(ctx context.Context, obj *model.User) ([]*model.Comment, error) {
	//panic(fmt.Errorf("not implemented: Comments - comments"))
	// return []*model.Comment{}, nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type commentResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
